### ISSUE TITLE
The program appears to have been executed twice without the start of training.  

### ISSUE THREAD

**Issue by Lululu100** [hulianyuyy/STGAT#11]
Hello, I ran into a problem when I was executing train.py.  The program appears to have been executed twice without the start of training.  Have you ever encountered similar problems? Looking forward to your reply.

D:\software\Anaconda3\envs\pytorch\python.exe E:\Study\Code\STGAT-main\train_val_test\train.py -config ../train_val_test/config/ntu/ntu60_dsta.yaml 
**Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:28:38) [MSC v.1929 64 bit (AMD64)] on win32
Good Luck
log_dir: ./work_dir/ntu60/baseline already exist
delete it? y/n:y
Dir removed: ./work_dir/ntu60/baseline**
refresh it
  [3.959s] batch_size: 32
  [3.960s] class_num: 60
  [3.960s] config: ../train_val_test/config/ntu/ntu60_dsta.yaml
  [3.960s] cuda_visible_device: 0
  [3.960s] data: ntu_skeleton
  [3.960s] data_param: {'train_data_param': {'data_path': 'E:\\Study\\Code\\STGAT-main\\ntu_60\\xsub\\train_data_joint.npy', 'label_path': 'E:\\Study\\Code\\STGAT-main\\ntu_60\\xsub\\train_label.pkl', 'random_choose': True, 'center_choose': False, 'window_size': 150, 'final_size': 128, 'num_skip_frame': None, 'decouple_spatial': False}, 'val_data_param': {'data_path': 'E:\\Study\\Code\\STGAT-main\\ntu_60\\xsub\\val_data_joint.npy', 'label_path': 'E:\\Study\\Code\\STGAT-main\\ntu_60\\xsub\\val_label.pkl', 'random_choose': False, 'center_choose': True, 'window_size': 150, 'final_size': 128, 'num_skip_frame': None, 'decouple_spatial': False}}
  [3.960s] debug: False
  [3.961s] device_id: [0]
  [3.961s] freeze_keys: []
  [3.961s] grad_clip: 0
  [3.961s] ignore_weights: ['fc']
  [3.961s] label_smoothing_num: 0
  [3.961s] last_model: None
  [3.961s] loss: cross_entropy
  [3.961s] lr: 0.1
  [3.961s] lr_decay_ratio: 0.1
  [3.961s] lr_multi_keys: []
  [3.962s] lr_param: {'step': [60, 90]}
  [3.962s] lr_scheduler: reduce_by_epoch
  [3.962s] ls_param: {}
  [3.962s] max_epoch: 120
  [3.962s] mix_up_num: 0
  [3.962s] mode: train_val
  [3.962s] model: st2ransformer_dsta
  [3.962s] model_param: {'num_point': 25, 'num_frame': 128, 'num_subset': 8, 'num_person': 2, 'glo_reg_s': True, 'att_s': True, 'glo_reg_t': False, 'att_t': False, 'dropout': 0, 'attentiondrop': 0, 'dropout2d': 0, 'use_spatial_att': True, 'use_temporal_att': False, 'use_pet': False, 'use_pes': False, 'config': [[64, 64, 16, 1], [64, 64, 16, 1], [64, 128, 32, 2], [128, 128, 32, 1], [128, 256, 64, 2], [256, 256, 64, 1], [256, 256, 64, 1], [256, 256, 64, 1]]}
  [3.962s] model_saved_name: ./work_dir/ntu60/baseline
  [3.962s] num_epoch_per_save: 10
  [3.962s] optimizer: sgd_nev
  [3.962s] pin_memory: False
  [3.963s] pre_trained_model: None
  [3.963s] step: [80]
  [3.963s] train: classify
  [3.963s] val_first: False
  [3.963s] warm_up_epoch: 5
  [3.963s] wd: 0.0005
  [3.963s] worker: 16
  [4.017s] work dir: ./work_dir/ntu60/baseline
  [4.195s] Model load finished: st2ransformer_dsta mode: train
  [4.379s] copy model to gpu
  [4.385s] Using SGD with momentum 0.9and nesterov
  [4.483s] no pretrained optimizer is loaded
  [4.484s] Using loss: cross_entropy
  [4.492s] Data load finished: ntu_skeleton
  [4.492s] lr scheduler: Reduce by epoch, step: [60, 90]
  [4.524s] Model total number of params: 5607740
  [4.526s] start epoch 0 -> max epoch 120

  [4.527s] Epoch : 0, Current lr: 0.02
**Process: ./work_dir/ntu60/baseline:   0%|          | 0/120 [00:00<?, ?it/s]Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:28:38) [MSC v.1929 64 bit (AMD64)] on win32
Good Luck
log_dir: ./work_dir/ntu60/baseline already exist
delete it? y/n:y
  [1.762s] Operation failed**

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\software\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\software\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\software\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\software\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\software\Anaconda3\envs\pytorch\lib\runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\software\Anaconda3\envs\pytorch\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\software\Anaconda3\envs\pytorch\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Study\Code\STGAT-main\train_val_test\train.py", line 58, in <module>
    args = parser_args.parser_args(block)
  File "E:\Study\Code\STGAT-main\train_val_test\parser_args.py", line 91, in parser_args
    shutil.rmtree(args.model_saved_name)
  File "D:\software\Anaconda3\envs\pytorch\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "D:\software\Anaconda3\envs\pytorch\lib\shutil.py", line 624, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "D:\software\Anaconda3\envs\pytorch\lib\shutil.py", line 629, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "D:\software\Anaconda3\envs\pytorch\lib\shutil.py", line 627, in _rmtree_unsafe
    os.unlink(fullname)
**PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: './work_dir/ntu60/baseline\\train\\events.out.tfevents.1683204383.lululu'**

**Comment by hulianyuyy** [comment]
This seems to be a common issue on Windows system. You can refer to [this](https://github.com/hulianyuyy/STGAT/issues/9#issuecomment-1370627877) for a solution.

**Comment by Lululu100** [comment]
Thank you for your reply. I tried to use the method proposed in the question area to solve the problem, but did not run the example successfully. I will try my best to do this work in the future. Thank you very much!
